version: '3.2'

services:
  db:
    container_name: ggce-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "ggce"
      POSTGRES_USER: "ggce"
      POSTGRES_DB: "ggce"
    ports:
      - 5432:5432
  rmq:
    container_name: ggce-rmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672